checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  environment:
    python:
      version: stackless-3.3.5
      # Whether to setup a virtual environment in the repository root directory.
      # Defaults to true if omitted.
      virtualenv: true
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - py-scrutinizer-run
          -
            command: pylint-run
            use_website_config: true
    tests: false
filter:
  excluded_paths:
    - '*/test/*'
  dependency_paths:
    - 'lib/*'
