services:
  faker-file:
    build:
      context: .
      args:
        - PYTHON_VERSION=${PYTHON_VERSION:-3.12}
    volumes:
      - .:/workspace              # Mount code
      - venvs_data:/opt/venvs     # Persist all venvs here

volumes:
  venvs_data:                     # This creates a persistent Docker volume
